# Generated by Django 5.0.6 on 2024-07-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0008_alter_restaurant_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('extendedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nagoyameshi.extendedmodel')),
                ('reservation_datetime', models.DateTimeField(verbose_name='予約日時')),
                ('number_of_persons', models.PositiveIntegerField(verbose_name='予約人数')),
                ('comment', models.CharField(max_length=200, verbose_name='コメント')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.restaurant', verbose_name='店舗')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            bases=('nagoyameshi.extendedmodel',),
        ),
    ]
