# Generated by Django 5.0.6 on 2024-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0010_alter_reservation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='thumbnail',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='nagoyameshi/restaurant/thumbnail', verbose_name='サムネイル'),
        ),
    ]
