# Generated by Django 5.0.6 on 2024-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0011_restaurant_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='thumbnail',
            field=models.ImageField(blank=True, default='upload/album/photo/noimage.png', upload_to='nagoyameshi/restaurant/thumbnail', verbose_name='サムネイル'),
        ),
    ]
